### ISSUE TITLE
zig cc build for ios can not find <stdio.h>

### ISSUE THREAD

**Issue by calvin2021y** [kubkon/zig-ios-example#6]
```sh
zig cc -target aarch64-ios -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk  -Ithird_party/utf8_range -c utf8_range/range2-neon.c -o ./range2-neon.c.o 
```

```sh
third_party/utf8_range/range2-neon.c:7:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
```

**Comment by kubkon** [comment]
I don't see how this issue is related to the contents of this repo, so please in the future refrain from submitting issues which look like generic "asking for help" question. Instead, I strongly recommend joining [Zig's discord](https://discord.gg/gxsFFjE) and asking the question there.

In the meantime, when specifying the sysroot for `zig cc` you also need to specify where to find the headers, and so in your particular case, you should also include `-I/usr/include` flag in your `zig cc` invocation.
